export enum ActionTypeStates {
    REQUEST = "REQUEST",
    SUCCESS = "SUCCESS",
    ERROR = "ERROR" 
}
export enum ActionTypeKeys {
    GET_FEED_REQUEST = "GET_FEED_REQUEST",
    GET_FEED_SUCCESS = "GET_FEED_SUCCESS",
    GET_FEED_FAILURE = "GET_FEED_FAILURE",
    GET_FEED_COMPONENT_SUCCESS = "GET_FEED_COMPONENT_SUCCESS",
    GET_FEED_COMPONENT_FAILURE = "GET_FEED_COMPONENT_FAILURE",
    GET_FEED_COMPONENT_REQUEST = "GET_FEED_COMPONENT_REQUEST",
}